# Generated by Django 3.0.1 on 2020-01-14 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200106_2359'),
        ('message', '0003_auto_20200113_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment.Equipment'),
        ),
    ]
