# Generated by Django 3.0.1 on 2020-01-14 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20200113_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 2, 26, 39, 142853, tzinfo=utc)),
        ),
    ]
