# Generated by Django 3.0.1 on 2020-01-09 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200106_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 9, 32, 4, 224636, tzinfo=utc)),
        ),
    ]
