# Generated by Django 3.0 on 2019-12-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['title', 'created_at']},
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_type',
            field=models.CharField(blank=True, choices=[('p', 'personal'), ('f', 'family'), ('h', 'house'), ('m', 'misc'), ('s', 'school')], default='m', max_length=1),
        ),
    ]
