# Generated by Django 3.0.1 on 2019-12-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='tool_name',
            field=models.CharField(default='Hand Tools', max_length=100),
        ),
    ]
